name: Deploy textbook to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (YYYYMMDD). Leer lassen = heutiges Datum (UTC).'
        required: false
      checksum:
        type: boolean
        description: 'SHA256-Checksummen in Artikel aufnehmen'
        default: true
  push:
    branches: [ main ]
    paths:
      - 'tools/**'
      - 'schemas/**'
      - 'source/**'
      - '.github/workflows/deploy-pages.yml'
      - 'README.md'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Compute version
        id: ver
        shell: bash
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            V="${{ github.event.inputs.version }}"
          else
            V="$(date -u +%Y%m%d)"
          fi
          echo "v=$V" >> "$GITHUB_OUTPUT"
          echo "Using version: $V"

      - name: Build manifests
        shell: bash
        run: |
          mkdir -p cdn
          EXTRA=""
          if [ "${{ github.event.inputs.checksum }}" != "false" ]; then
            EXTRA="--checksum"
          fi
          node tools/build-manifests.mjs \
            --input ./source/v3_curated \
            --out ./cdn \
            --version "${{ steps.ver.outputs.v }}" \
            $EXTRA

      - name: Add .nojekyll
        run: echo > cdn/.nojekyll

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./cdn

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
